### ISSUE TITLE
Organize commands in to like categories

### ISSUE THREAD

**Issue by unklCharlos** [Advomatic/pantheon-tools#19]
Organize all the commands in to categories. e.g. deploy, report, update etc.

**Comment by Yuvania** [comment]
Could I take this issue? 
Or is someone already working on it?

**Comment by dalin-** [comment]
@Yuvania Go for it!

**Comment by unklCharlos** [comment]
@Yuvania It is fine for you to take on. However I realized I didn't mention README anywhere. I was just thinking if the README was organized devs who are new to the tools could locate the commands faster. I realize this could be interpreted as restructuring the commands in to their own directories which I hadn't considered.
