### ISSUE TITLE
Error thrown after cloning database from live to deployment environment.

### ISSUE THREAD

**Issue by duncancm9** [Advomatic/pantheon-tools#27]
Received error after cloning database from live to deployment environment.

`[error]  Successfully queued endpoint_clear_framework_cache`

![CleanShot 2024-02-29 at 12 37 21@2x](https://github.com/fourkitchens/pantheon-tools/assets/8762630/07f16c4e-0370-404f-9035-0e0295b0ff4d)

Appears to be intermittent and not sure exactly what caused it.

**Comment by dalin-** [comment]
@duncancm9 I think you found a terminus bug, not `pantheon-tools`.
